### ISSUE TITLE
제안 글 이미지 첨부

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/parti-mx#15]
html 편집기 rich text editor 쓰지 않고, 이미지 따로 첨부한다. 
- 이미지 첨부 시 바로 서버에 올리지 않고, 저장 시에만 올린다. (페이스북은 클릭 시 바로 서버 올림? 왜?)
- [이미지 필드 속성은 array로 만든다](https://hasura.io/docs/1.0/graphql/manual/mutations/insert.html#insert-an-object-with-an-array-field)
- 글 등록/수정 페이지
  - [x] 이미지 첨부
  - [x] 이미지 삭제
- [x] 상세 페이지 이미지 보기

**Comment by rest515** [comment]
에디터는 웹 버전에서만 제공하는 것으로 정리하시죠.

**Comment by iamswain25** [comment]
> 에디터는 웹 버전에서만 제공하는 것으로 정리하시죠.

현재 pure text 보여주는 곳을 나중에 웹 버전 에디터가 들어갈 시 앱에서는 webview로 html 과 pure text 모두 보여주는 걸로 수정할게요.

**Comment by rest515** [comment]
네 우선은 신경쓰지 마시고 그냥 pure text 처리만 해보아요.

**Comment by iamswain25** [comment]
이미지 첨부 완성했습니다. 핸드폰으로 직접 확인하니 디테일 작업이 더 필요할 것 같습니다.
우선순위는 페어때 확인하면 좋을 것 같아요.
- [ ] 이미지 클릭하여 크게 보기
  - [ ] 이미지 스와이핑 연속으로 보기
- [ ] 이미지 다운로드

**Comment by rest515** [comment]
다운로드까진 일단 안 해도 될 것 같습니다. 크게 보기랑 스와이핑까지만 구현하면 어떨까요.

**Comment by iamswain25** [comment]
https://github.com/ascoders/react-native-image-viewer 검색해서 제일 위에 뜨는걸로 엮을게요 ㅎㅎ

**Comment by iamswain25** [comment]
이미지 클릭 시 마다 로딩 시간이 꽤 걸려서 이미지 보이는 부분을 모두 캐시 매니저로 변경하겠습니다.
https://github.com/wcandillon/react-native-expo-image-cache
