### ISSUE TITLE
로그아웃 후 다른 계정으로 로그인 시 나오는 화면

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/parti-mx#29]
로그아웃 후 다른 계정으로 로그인 시 이전 로그인 계정에서 사용했던 마지막 그룹 홈 화면이 표시됩니다.

**Comment by iamswain25** [comment]
@anne-parti @rest515 이건 일단 일부러 이렇게 했습니다.. 
1. 로그아웃 시 마지막 들어간 그룹 정보를 지워서 새로 로그인 시 그룹 선택 사이드바가 나오는 방안이 있습니다.
2. 기기 대신 디비에 마지막 접속 그룹을 저장 하는 방안이 있습니다.

**Comment by iamswain25** [comment]
일단 1번으로 로그아웃 시 리셋합니다.

**Comment by anne-parti** [comment]
@iamswain25 로그아웃 했다 로그인 하는 모든 경우(같은 아이디로 로그아웃, 재로그인 시 포함)에 사이드바 화면을 보여주는거죠?

**Comment by iamswain25** [comment]
> @iamswain25 로그아웃 했다 로그인 하는 모든 경우(같은 아이디로 로그아웃, 재로그인 시 포함)에 사이드바 화면을 보여주는거죠?

네 맞습니다.

**Comment by anne-parti** [comment]
확인했습니다~
