### ISSUE TITLE
멤버 하단 정보 (이메일? 시간?)

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/parti-mx#31]
그룹 관리 > 멤버 하단에 Invalid date 라고 표시됩니다. 목업 기획서에는 이메일주소, 디자인에는 시간으로 표시되어 있는데 뭐가 맞는건가요? 시간은 어떤 의미인지도 궁금합니다.

**Comment by iamswain25** [comment]
@anne-parti 일단은 목업 기획서 따라 이메일로 변경할게요!

**Comment by anne-parti** [comment]
확인했습니다.
