### ISSUE TITLE
댓글 닉네임 우측에 "동의" 디자인

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/parti-mx#32]
> @anne-parti [제안] 제안에 동의 후에 댓글 달면 닉네임 우측에 동의 라고 추가되는데요. 별도 디자인이 없나요? 지금 구현된걸로는 닉네임이 OO동의 이렇게로 인식됩니다.

**Comment by iamswain25** [comment]
디자인에는 없어서 일단 기본 민트색으로 변경해 놓을게요.

**Comment by anne-parti** [comment]
@iamswain25 수정된 것 확인했습니다. 지금 이 이슈 클로즈 되어 있는데요. 디자인 확인 및 검토 필요할 경우 다시 오픈해주세요.

**Comment by anne-parti** [comment]
@iamswain25 다시 보니까 동의가 아래 댓글 달기 신고하기랑 색상, 크기가 동일해서 꼭 누를 수 있는 버튼처럼도 보이네요.. 한 번 디자인 잡긴 해야할 것 같아요~
