### ISSUE TITLE
그룹홈>그룹명 입력시 커서 안보임

### ISSUE THREAD

**Issue by trulyj501** [parti-coop/parti-mx#54]
그룹명 입력시 커서가 보이지 않아요.

**Comment by iamswain25** [comment]
https://github.com/facebook/react-native/issues/22762#issuecomment-622235721 
아이폰은 커서를 하얀색으로 바꿀 수 있는데 안드로이드는 적용이 아마 6개월 뒤나 가능할것 같습니다 ㅜㅜ
