### ISSUE TITLE
제안 게시판 "토론 정리 시 종료" 옵션 추가 

### ISSUE THREAD

**Issue by Dandi-hwang** [parti-coop/parti-mx#86]
- [ ] 베타 기간 중에는 게시물 참여가 적으니 오래 열어두고 봐야 해서 

- [ ] https://parti.mx/post/368 완료되버린 첫번째 제안. 다시 진행중으로 바꿔주기.

**Comment by iamswain25** [comment]
처리해서 배포했습니다. 확인 후 종료 부탁드립니다.
